language: php

env:
  global:
    - PHPUNIT_FLAGS="-v"

matrix:
  fast_finish: true
  include:
    - php: 7.4

install:
  - composer install

script:
  - vendor/bin/psalm
  - vendor/bin/phpunit
  - vendor/bin/codecept run
